### ISSUE TITLE
Copyright adjustment as time brings us to 2014

### ISSUE THREAD

**Issue by nickl-** [Respect/project-info#12]
Update all the licenses to reflect copyright YYYY-2013

**Comment by nickl-** [comment]
https://github.com/Respect/Rest/commit/cb92aa4c6b9308576937aeb4f1ea6da14c2fe845#commitcomment-2465473
https://github.com/Respect/Validation/commit/4dbe3f0bf8c896baacb8bd06d0076e3a0c0e0e14
https://github.com/Respect/Data/commit/1516795c4b8541134fe8fae3623f9bcfff36907a
https://github.com/Respect/Relational/commit/b2b617fd7d227614481de6563fa9f1a67a68b7eb
https://github.com/Respect/Config/commit/74f66433cc9686296b0a7b81483e04e5d3e5cdd9
https://github.com/Respect/Structural/commit/711d1df461fc0b5e7df4bde2a4b53d41e3898df4
https://github.com/Respect/Http/commit/ba5bb7777270f5c8e01aa4896974257fad4d0551
https://github.com/Respect/Template/commit/a12f60ca5948c74f510403f1bf9dfa4dcef0de48
https://github.com/Respect/Conversion/commit/a3739c6b52ebc0fc3e07655573e70aef37a8de77
https://github.com/Respect/Doc/commit/19072e220de42b2f74538f0ca113ffc09dc332fd
https://github.com/Respect/Foundation/commit/1c07ce8adabbd45634bb9c8914f1053be6c0731b

**Comment by henriquemoody** [comment]
![\o/](http://blog.uber.com/wp-content/uploads/2013/01/funny-gif-excited-kid-baby-happy-1.gif)

**Comment by nickl-** [comment]
@henriquemoody :thumbsup: That's so cute :heart_eyes:

**Comment by nickl-** [comment]
It's that time again, please update all licenses to 2014 and post the commits here for reference.

See https://github.com/Respect/project-info/issues/12#issuecomment-12463238 for an example.

**Comment by nickl-** [comment]
@claudson thank you for all the updates now push them upstream please.

You have commit rights because we deemed you qualified. Instead of review before commit (which is submitting PRs) you and all the pandas, me as well, now have commit-followed by review. It is also part of your responsibility to check everything we commit and provide comments (if only to stow that you did the review and found nothing else to comment on)

Agreed?

**Comment by nickl-** [comment]
Oops: Unless you don't have commit rights on the other projects @alganet can you confirm please?
