### ISSUE TITLE
Membership request on PHP-FIG

### ISSUE THREAD

**Issue by henriquemoody** [Respect/project-info#5]
People, what you think about a membership request (of @alganet) to PHP-FIG?

**Comment by wesleyvicthor** [comment]
I was thinking about it too.
When I saw the list of memberships and all those, i think: Oh, maybe could be here Alexandre Gaigalas (Respect)
ho ho ho.

**Comment by henriquemoody** [comment]
hehehehhee

**Comment by alganet** [comment]
I'm very proud you guys considered this =) I'd be glad to represent Respect there.

I feel that many projects are in PHP-FIG without a clear purpouse. They don't want to improve any specific aspect of interop, and most times the proposals are vague enough to cause confusion, chaos and sad pandas.

For us to join PHP-FIG, I believe we need to define a clear purpouse in the context of interop. 

What could we do to improve **all** framework interoperability (fig members or not)?

**Comment by nickl-** [comment]
I don't know if it will make a difference there's already 23 voting members is that not enough? I am all for interop and and adopting standards but as @alganet says, what is the purpose. 

It is going to take up a lot of time, time I would prefer Alexandre spends in Respect-land and not in PHP-the-world-land, the project is still an infant and there are many decisions to make and things to get done. If you think you have time to uhm and ah over what is the best type of sugar by all means go for it! I just don't see Respect benefitting from it in anyway.

As long as we are represented on packagist our code/style/practices are being considered, there we already have more votes through presence alone than 1 vote on the voting members list is going to give us. I say lets get more projects finished and conforming to the current PSR requirements and packaged and on the package manager if you really want to make a difference as to the standards and the mood of all pandas.

My 2c

**Comment by wesleyvicthor** [comment]
good point @nickl-.  I agree.

**Comment by henriquemoody** [comment]
+1

**Comment by nickl-** [comment]
I have no doubt though... that @alganet... would make for a delicious FIG =)
