### ISSUE TITLE
Respect on ohloh

### ISSUE THREAD

**Issue by nickl-** [Respect/project-info#9]
Respect projects have been added to ohloh https://www.ohloh.net/p?q=Respect once processed you can go claim your committer role and attach to your profile.

**Comment by henriquemoody** [comment]
Nice one! =)

**Comment by henriquemoody** [comment]
It's more easy to do it with https://www.ohloh.net/people/rankings?query={YOURNAME}&sort=kudo_position

**Comment by nickl-** [comment]
How cool are the banners? http://documentup.com/respect/rest works on documentUp and then I realized that they break our other cool links so... I logged an existing issue https://github.com/jeromegn/DocumentUp/issues/58 forked the project and digging through coffeescript to find a fix for it.

P.S> don't be shy with those Kudos though =)

**Comment by henriquemoody** [comment]
I think we must discuss this kind of thinks on Gitter.
